In [1]:
def jukaiki_bunseki(x1, x2, y):
 
 N = np.size(x1) # 標本数
 Y = np.c_[y]
 X = np.c_[x1, x2, np.ones(N)]
 
 tmp = np.dot(X.T, X) # XTX
 r1 = np.linalg.inv(tmp) # (XTX)^-1 逆行列
 r2 = np.dot(X.T, Y) # XTY
 A = np.dot(r1, r2) # 係数ベクトル
 
 a1 = A[0] # 傾き
 a2 = A[1] # 傾き
 b = A[2] # 切片b
 
 # [追加機能] 回帰直線の妥当性を評価する
 Y_hat = a1*x1+a2*x2+b # 予測値
 C = np.corrcoef(Y_hat, y)[0,1] # 相関係数
 # 決定係数
 R2 = np.sum( (Y_hat-np.mean(y))**2 ) / np.sum( (y-np.mean(y))**2 )
 
 return a1, a2, b, C, R2

In [2]:
def jukaiki_bunseki(x1, x2, x3, y):
 
 N = np.size(x1) # 標本数
 Y = np.c_[y]
 X = np.c_[x1, x2, x3, np.ones(N)]
 
 tmp = np.dot(X.T, X) # XTX
 r1 = np.linalg.inv(tmp) # (XTX)^-1 逆行列
 r2 = np.dot(X.T, Y) # XTY
 A = np.dot(r1, r2) # 係数ベクトル
 
 a1 = A[0] # 傾き
 a2 = A[1] # 傾き
 a3 = A[2] # 傾き
 b = A[3] # 切片b
 
 # [追加機能] 回帰直線の妥当性を評価する
 Y_hat = a1*x1+a2*x2+a3*x3+b # 予測値
 C = np.corrcoef(Y_hat, y)[0,1] # 相関係数
 # 決定係数
 R2 = np.sum( (Y_hat-np.mean(y))**2 ) / np.sum( (y-np.mean(y))**2 )
 
 return a1, a2, a3, b, C, R2

In [15]:
def jukaiki_bunseki(X, y):
 
    N = np.size(y) # 標本数
    Y = np.c_[y]
    X = np.c_[X, np.ones(N)]
 
    tmp = np.dot(X.T, X)
    r1 = np.linalg.inv(tmp)
    r2 = np.dot(X.T, Y)
    A = np.dot(r1, r2) # 係数ベクトル
 
    Y_hat = np.dot(X, A) # 内積 (予測値): a1*x1+a2*x2+...+b*1
    Y_hat = Y_hat[:, 0] # 0列のみを指定 (行列→ベクトル)
 
    C = np.corrcoef(Y_hat, y)[0,1]
    R2 = np.sum( (Y_hat-np.mean(y))**2 ) / np.sum( (y-np.mean(y))**2 )
 
    return A, C, R2

In [16]:
import numpy as np 
x1 = [8,7,5,4,6,2,3,9]
x2 = [8,7,9,3,8,3,6,7]
y = [18,12,14,6,12,8,10,16]
X = np.c_[x1, x2]

In [17]:
A, C, R2 = jukaiki_bunseki(X, y)
print(A)
print(C)
print(R2)

[[0.81081081]
 [0.8957529 ]
 [1.83011583]]
0.9062508915490984
0.8212906784335335


In [18]:
X

array([[8, 8],
       [7, 7],
       [5, 9],
       [4, 3],
       [6, 8],
       [2, 3],
       [3, 6],
       [9, 7]])

In [19]:
A

array([[0.81081081],
       [0.8957529 ],
       [1.83011583]])

In [20]:
Y_hat

NameError: name 'Y_hat' is not defined

In [21]:
x1 = [8,7,5,4,6,2,3,9]
x2 = [8,7,9,3,8,3,6,7]
x3 = [4,7,8,3,8,5,6,9]
y = [18,12,14,6,12,8,10,16]
X = np.c_[x1, x2, x3]

In [22]:
A, C, R2 = jukaiki_bunseki(X, y)
print(A)
print(C)
print(R2)

[[ 0.81611811]
 [ 1.05497199]
 [-0.2749183 ]
 [ 2.50414332]]
0.9132618247418858
0.8340471605308782


In [23]:
x1_h = (x1-np.mean(x1)) / np.std(x1, ddof=1)
x2_h = (x2-np.mean(x2)) / np.std(x2, ddof=1)
x3_h = (x3-np.mean(x3)) / np.std(x3, ddof=1)
y_h = (y-np.mean(y)) / np.std(y, ddof=1)
X_h = np.c_[x1_h, x2_h, x3_h]

In [24]:
A, C, R2 = jukaiki_bunseki(X_h, y_h)
print(A)
print(C)
print(R2)

[[ 4.99768237e-01]
 [ 5.97073604e-01]
 [-1.45797446e-01]
 [ 9.72832471e-18]]
0.9132618247418858
0.834047160530879


In [25]:
x1=[3,5,2,4,4,5,1,1,4,4,5,2,5,1,2] 
x2=[3,4,2,4,4,4,3,2,4,3,4,2,5,2,2] 
x3=[4,2,2,3,2,2,3,3,5,4,2,2,1,4,2] 
y=[3,2,1,2,3,1,3,1,5,3,3,1,4,1,1] 
N = np.size(y) 
X = np.c_[x1, x2, x3] 
A, C, R2 = jukaiki_bunseki(X, y) 
print(A) 
print(C) 
print(R2)

[[-0.27524303]
 [ 1.33115731]
 [ 0.50904704]
 [-2.5036543 ]]
0.8272730306826338
0.6843806672948289


In [26]:
x1_h = (x1-np.mean(x1)) / np.std(x1, ddof=1)
x2_h = (x2-np.mean(x2)) / np.std(x2, ddof=1)
x3_h = (x3-np.mean(x3)) / np.std(x3, ddof=1)
y_h = (y-np.mean(y)) / np.std(y, ddof=1)
X_h = np.c_[x1_h, x2_h, x3_h]

In [27]:
A, C, R2 = jukaiki_bunseki(X_h, y_h)
print(A)
print(C)
print(R2)

[[-3.37102487e-01]
 [ 1.05481680e+00]
 [ 4.37416899e-01]
 [ 2.10543807e-16]]
0.8272730306826341
0.6843806672948298


In [29]:
A, C, R2 = jukaiki_bunseki( np.c_[x1_h, x3_h], y_h) 
print(A) 
print(C) 
print(R2)

[[5.87835518e-01]
 [4.58861357e-01]
 [1.26653055e-16]]
0.6461592625119486
0.4175217925299851


In [31]:
A, C, R2 = jukaiki_bunseki(x1_h, x2_h) 
print(A) 
print(C) 
print(R2)

[[ 8.71648250e-01]
 [-8.08632883e-17]]
0.8716482500611272
0.759770671834625


In [32]:
A, C, R2 = jukaiki_bunseki(x1_h, x3_h) 
print(A) 
print(C) 
print(R2)

[[-2.56886475e-01]
 [-6.55275621e-17]]
0.2568864750256221
0.0659906610510896


In [33]:
np.corrcoef(x1_h, y_h)[0,1]

0.46996024134793524